# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: mac-wifi-cleaner
    main: .
    binary: mac-wifi-cleaner
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - README.md

homebrew_casks:
  - name: mac-wifi-cleaner
    commit_author:
      name: Jens Hilligsøe
      email: github@hilli.dk
    commit_msg_template: "Brew cask update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/hilli/mac-wifi-cleaner"
    description: "Clean up the long list of preferred Wi-Fi networks on your Mac"
    url:
      verified: github.com/hilli/mac-wifi-cleaner
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mac-wifi-cleaner"]
          end
    repository:
      owner: hilli
      name: homebrew-tap
      branch: release-mac-wifi-cleaner-{{.Tag}}
      pull_request:
        enabled: true
        draft: false

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
